---
- name: Setting Configurations
  block:
    - name: Disabling named if exists
      service:
        name: systemd-resolved
        state: stopped
        enabled: false
      
    - name: Deploying general configuration file.
      template:
        src: general.conf.j2
        dest: /etc/unbound/unbound.conf.d/general.conf

    - name: Creating unbound log file.
      file:
        state: touch
        path: /var/log/unbound.log
        owner: unbound
        group: unbound

    - name: Deploying forward configuration file.
      template:
        src: forwards.conf.j2
        dest: /etc/unbound/unbound.conf.d/forwards.conf

    - name: Deploying Trusted Domains configuration file.
      template:
        src: trusted_domains.conf.j2
        dest: /etc/unbound/unbound.conf.d/trusted_domains.conf

    - name: Set value com sysctl to memory
      sysctl:
        name: "{{ item }}"
        value: '4194304'
      loop: 
        - net.core.rmem_max
        - net.core.wmem_max

    - name: Configuring Apparmor
      lineinfile:
        line: '/var/log/unbound.log rw,'
        path: /etc/apparmor.d/local/usr.sbin.unbound

    - name: Applying new configurations on Apparmor 
      shell:
        cmd: apparmor_parser -r /etc/apparmor.d/usr.sbin.unbound

    - name: Install openresolv
      apt:
        name: openresolv
        state: latest

    - name: Set resolv.conf to localhost always
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

  always:
    - name: Restart unbound
      service: 
        name: unbound
        state: restarted
